### ISSUE TITLE
Validation error when multiple working group is selected for FH Registry

### ISSUE THREAD

**Issue by aminur80** [muccg/rdrf#733] opened 2019-01-18 02:28 UTC
**Description:**
Multiple working groups are auto selected when the user mistakenly select multiple groups and after that trying to select a single group and save.

**Steps to reproduce:**
1) Login as Admin user
2) Select a patient from FH registry
3) Can see that the patient belongs to one working group (center)
4) Select multiple working group by clicking on the working group while pressing Ctrl key
5) Save the Patient
6) See the following validation error - 
`Please correct errors below:
Patient all : Patient can only belong to one working group per registry. Patient is assigned to more than one working for FH Registry`  
7) Select only one working group by clicking one of the working group
8) Save the patient with success
9) Can see that multiple working groups are still selected
10) Click on Save and we get the validation error again.

**Expected Result:**
For FH registry only one working group can be selected for a patient

**Comment by id2359** [comment] 2019-01-18 03:18
Works on staging 1.10 but seems to be a regression due to upgrade.

**Comment by id2359** [comment] 2019-01-21 04:45
Actually it's a side effect of being
able to

assign p to working group a and save ok
then assign p to working group b and save ok

but the actually operation being performed was adding the wgs to a union set

p assigned to a,b
which is then invalid ( if further ops done on the client side)

**Closed by id2359** 2019-01-21 04:45 UTC
Labels: type/bug
