### ISSUE TITLE
CIC Breast: Odd character in CDE TARGETTX

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1411] opened 2020-07-01 05:33 UTC
On the patient's Treatment page, for the cde `TARGETTX`. The option for "Her-2 targeting therapy" contains an odd character. The dash does not appear to be a regular Unicode or ASCII character.

Exact string as appears in the HTML;

```

 Her‐2 targeting therapy
```

**Comment by id2359** [comment] 2020-07-02 07:36
dupe of https://github.com/muccg/rdrf/issues/1412

**Closed** 2020-07-02 07:37 UTC
Labels: area/breastcancer, area/cic, type/duplicate
